# Generated by Django 4.2.30 on 2026-09-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_user'),
        ('documents', '0002_flashcard_roadmap'),
    ]

    operations = [
    ]
